### ISSUE TITLE
데이터

### ISSUE THREAD

**Issue by ghost** [DatathonInfo/AIDD2021#21]
csv파일로 된 데이터를 어디서 볼수있나요? 따로 명령어가 있나요?

**Comment by DatathonInfo** [comment]
안녕하세요, 참가자님.

사전 안내 자료에는 csv 파일로 설명이 되었으나, 
nsml 시스템상 현재 확장자 없이 올라가있는 상태입니다. 

참고 부탁드립니다.

감사합니다.

A.I.D.D. 2021 운영팀 드림.

**Comment by DatathonInfo** [comment]
추가로 답변드리자면,

nsml run에 작동하는 main.py에서
```python
import os
import pandas as pd
import nsml
from nsml import DATASET_PATH

train_data_path = os.path.join(DATASET_PATH, 'train', 'train_data')
train_data = pd.read_csv(train_data_path)
```
위와 같은 코드로 csv 형태의 Train Data에 접근할 수 있습니다.


감사합니다.
A.I.D.D. 2021 운영팀

**Comment by danbkim93** [comment]
> 추가로 답변드리자면,
> 
> nsml run에 작동하는 main.py에서
> 
> ```python
> import os
> import pandas as pd
> import nsml
> from nsml import DATASET_PATH
> 
> train_data_path = os.path.join(DATASET_PATH, train, train_data)
> train_data = pd.read_csv(train_data_path)
> ```
> 
> 위와 같은 코드로 csv 형태의 Train Data에 접근할 수 있습니다.
> 
> 감사합니다. A.I.D.D. 2021 운영팀

위에 적어주신 os.path.join(DATASET_PATH, train, train_data) 에서 argument 안에 있는 train 과 train_data 의 object 형태가 무엇인지 알 수 있을까요?

**Comment by danbkim93** [comment]
> 추가로 답변드리자면,
> 
> nsml run에 작동하는 main.py에서
> 
> ```python
> import os
> import pandas as pd
> import nsml
> from nsml import DATASET_PATH
> 
> train_data_path = os.path.join(DATASET_PATH, train, train_data)
> train_data = pd.read_csv(train_data_path)
> ```
> 
> 위와 같은 코드로 csv 형태의 Train Data에 접근할 수 있습니다.
> 
> 감사합니다. A.I.D.D. 2021 운영팀
 

두가지 질문이 있습니다. 
 
1) os.path.join(DATASET_PATH, train, train_data) 에서 train 과 train_data 가 main.py 에 define 되어 있지 않아서 
./nsml logs AID015/nia_dm_prelim/19 라고 입력 할 경우, 
아래와 같이 출력되고 있습니다.

Traceback (most recent call last):
  File "main.py", line 19, in <module>
    train_data_path = os.path.join(DATASET_PATH, train, train_data)
NameError: name 'train' is not defined
 
train 은 저희가 따로 main.py 에서 정의 해야하나요?

2) 터미널에서 ./nsml run -d nia_dm_prelim 라고 입력할 경우 "Session AID015/nia_dm_prelim/19 is started" 라고만 출력되고 있습니다. 이 상황에서 데이터를 보려면 어떤 단계를 거쳐야 하나요? 


감사합니다.

**Comment by pdxen-jisun** [comment]
> > 추가로 답변드리자면,
> > nsml run에 작동하는 main.py에서
> > ```python
> > import os
> > import pandas as pd
> > import nsml
> > from nsml import DATASET_PATH
> > 
> > train_data_path = os.path.join(DATASET_PATH, train, train_data)
> > train_data = pd.read_csv(train_data_path)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 위와 같은 코드로 csv 형태의 Train Data에 접근할 수 있습니다.
> > 감사합니다. A.I.D.D. 2021 운영팀
> 
> 두가지 질문이 있습니다.
> 
> 1. os.path.join(DATASET_PATH, train, train_data) 에서 train 과 train_data 가 main.py 에 define 되어 있지 않아서
>    ./nsml logs AID015/nia_dm_prelim/19 라고 입력 할 경우,
>    아래와 같이 출력되고 있습니다.
> 
> Traceback (most recent call last): File "main.py", line 19, in train_data_path = os.path.join(DATASET_PATH, train, train_data) NameError: name 'train' is not defined
> 
> train 은 저희가 따로 main.py 에서 정의 해야하나요?
> 
> 2. 터미널에서 ./nsml run -d nia_dm_prelim 라고 입력할 경우 "Session AID015/nia_dm_prelim/19 is started" 라고만 출력되고 있습니다. 이 상황에서 데이터를 보려면 어떤 단계를 거쳐야 하나요?
> 
> 감사합니다.

train, train_data는 스트링입니다.
베이스라인 보시면 data_path, label_path 있어요.
