### ISSUE TITLE
xgboost 오류

### ISSUE THREAD

**Issue by hjk1996** [DatathonInfo/AIDD2021#77]
xgboost를 사용하려고 하는데 다음과 같은 오류가 발생합니다.
local에서는 import 잘 되는데 nsml 상에서는 setup에서 xgboost 설정해줘도 오류가 뜨네요

```
Traceback (most recent call last):
  File "xg_optimization.py", line 15, in <module>
    import xgboost as xgb
  File "/app/xgboost.py", line 15, in <module>
    from xgboost import XGBClassifier
ImportError: cannot import name 'XGBClassifier' from 'xgboost' (/app/xgboost.py)
User session exited
```

**Comment by DatathonInfo** [comment]
안녕하세요 참가자님,

참가자님이 작성하신 코드중
`xgboost.py`에서
```python
from xgboost import XGBClassifier
```
부분이 import 하는 xgboost가 python site-package가 아닌,
함께 제출하신 `xgboost.py`를 참조하는 것으로 보입니다.

제출된 `xgboost.py`의 파일명을 바꿔주시면 감사하겠습니다.


감사합니다.
A.I.D.D. 2021 운영팀 드림
